Traducao de Retry-ability
pedrohyvo/cypress-docs-pt-br pull request #104
Opened 2023-01-23 14:43 UTC by alineborak

2023-01-26 15:24 UTC, pedrohyvo commented
@alineborak você poderia corrigir as issues no lint da sua página, por favor

2023-01-26 15:33 UTC, alineborak commented
> @alineborak você poderia corrigir as issues no lint da sua página, por favor

Nao aparecem erros de lint para mim, como que eu resolvo isso?
Eu acho que nao aparece pq eu devo ter outras config baseada no projeto do trampo.

2023-01-26 15:40 UTC, pedrohyvo commented
> > @alineborak você poderia corrigir as issues no lint da sua página, por favor
> 
> Nao aparecem erros de lint para mim, como que eu resolvo isso? Eu acho que nao aparece pq eu devo ter outras config baseada no projeto do trampo.

Dá uma olhada aqui na página do guia - https://github.com/pedrohyvo/cypress-docs-pt-br/blob/master/CONTRIBUTING.md#como-rodar-o-markdown-lint-localmente
se precisar de ajuda, me chama no telegram com o mesmo usuario que o github, ta certo?

2023-01-26 18:22 UTC, pedrohyvo commented on pages/core-concepts/retry-ability.md
> +Freqüentemente, um comando Cypress possui asserções integradas que farão com que as consultas anteriores sejam repetidas.
```suggestion
Frequentemente, um comando Cypress possui asserções integradas que farão com que as consultas anteriores sejam repetidas.
```

2023-01-26 18:24 UTC, pedrohyvo requested changes
@alineborak faltou adicionar a sua página no README, no mais a sua tradução está excelente!! 🚀

2023-01-30 12:40 UTC, alineborak commented
> @alineborak faltou adicionar a sua página no README, no mais a sua tradução está excelente!! 🚀

Ola Pedro, acho que agora deu certo. Atualizei o ultimo comentario que vc deixou e tambem atualizei o readme. Me fala se ta tudo ok por favor.
Obrigada.

2023-01-30 12:44 UTC, pedrohyvo requested changes

2023-01-30 12:44 UTC, pedrohyvo commented on README.md
> +    <td align="center"><a href="https://github.com/alineborak"><img src="https://avatars.githubusercontent.com/u/36476341?v=4" width="100px;" alt=""/><br /><sub><b>Aline Bora</b></sub></a><br /><a hr
@alineborak nós temos um bot que faz essa adição automática dos contribuidores da página e não de forma manual. Você poderia remover essa parte e colocar a sua página na lista de páginas, por favor

2023-01-30 12:59 UTC, alineborak commented on README.md
> +    <td align="center"><a href="https://github.com/alineborak"><img src="https://avatars.githubusercontent.com/u/36476341?v=4" width="100px;" alt=""/><br /><sub><b>Aline Bora</b></sub></a><br /><a hr
Entao o que foi que vc pediu para atualizar o readme entao?

2023-01-30 13:02 UTC, alineborak commented on README.md
> +    <td align="center"><a href="https://github.com/alineborak"><img src="https://avatars.githubusercontent.com/u/36476341?v=4" width="100px;" alt=""/><br /><sub><b>Aline Bora</b></sub></a><br /><a hr
Feito.

2023-01-30 13:07 UTC, pedrohyvo approved these changes
Aprovado! @alineborak fique a vontade para pegar outra página, ta bem? obrigado pela contribuição!

2023-01-30 13:10 UTC, merged

2023-01-30 13:11 UTC, alineborak commented
> Aprovado! @alineborak fique a vontade para pegar outra página, ta bem? obrigado pela contribuição!

Beleza, pode deixar :) Vi que deu erros de lint em outros arquivos (que nao eh o meu). Normal isso?