Finished doc: Interacting with elements > core concepts
pedrohyvo/cypress-docs-pt-br pull request #54
Opened 2021-03-06 22:38 UTC by murillowelsi

2021-03-07 19:46 UTC, pedrohyvo reviewed
Obrigado pela contribuição @murillowelsi !! Deixei apenas alguns comentários e após isso ele está pronto para ser mergeado. Parabéns pela contribuição 🍰

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +- Como Cypress lida com elementos de animação
```suggestion
- Como o Cypress lida com elementos de animação
```

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +[//]: <> (TODO - Adicionar links - integração github)
O texto "integração github" deve ser trocado para dizer o que realmente são os links, nesse caso são: "comandos cypress", por exemplo. Entende?

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +Sempre que Cypress não pode interagir com um elemento, ele pode falhar em qualquer uma das etapas acima.
```suggestion
Sempre que o Cypress não pode interagir com um elemento, ele pode falhar em qualquer uma das etapas acima. 
Normalmente, você receberá um erro explicando por que o elemento não foi considerado acionável.
```

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +## Desabilidade
Não seria melhor "Inabilidade" ou "Incapacidade"?

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +O Cypress verifica se a propriedade `readonly` de um elemento é definida durante [`.type()`](https://docs.cypress.io/api/commands/type.html).
Você tem que adicionar sempre o TODO acima de todo bloco de texto que contém link que iremos atualzar após a página linkada ser traduzida, entendeu?

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +exceder o [`animationDistanceThreshold`](https://docs.cypress.io/guides/references/configuration.html#Actionability), então
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +Você também pode desligar nossas verificações de animações com a opção de configuração [`waitForAnimations`](https://docs.cypress.io/guides/references/configuration.html#Actionability).
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +interagir. Você sempre pode [`aumentar ou diminuir esse limite`](https://docs.cypress.io/guides/references/configuration.html#Actionability).
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +Nesses casos, o evento dispara no elemento filho. Nós até anotamos isso para você no [`Log de Comandos`](https://docs.cypress.io/guides/core-concepts/test-runner.html#Command-Log).
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +> visualização ao usar comandos DOM, como `cy.get()` ou `.find()`.
Falta adicionar os links e adicionar a linha TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +configuração [`scrollBehavior`](https://docs.cypress.io/guides/references/configuration.html#Actionability). Isso pode
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +As coordenadas nas quais disparamos o evento geralmente estarão disponíveis ao clicar no comando no [`Log de Comandos`](https://docs.cypress.io/guides/core-concepts/test-runner.html#Command-Log).
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +Ao usar o [`Log de comandos`](https://docs.cypress.io/guides/core-concepts/test-runner.html#Command-Log) para passar o
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +acima. Nós *não* rolamos elementos com os comandos DOM regulares como `cy.get()` ou `.find()`.
Falta linkas os comandos e colocar a linha TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +Recomendamos colocar `debugger` ou usar o comando [`.debug()`](https://docs.cypress.io/api/commands/debug.html)
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +Você também pode [`vincular a eventos`](https://docs.cypress.io/api/events/catalog-of-events.html) que o Cypress dispara
Adicionar link TODO

2021-03-07 19:46 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +> para mais detalhes.
Faltar link o comando select para a página e adicionar a linha TODO

2021-03-08 08:45 UTC, murillowelsi commented
As correções foram feitas, obrigado pelas dicas (:

2021-03-08 14:12 UTC, lucastfa-toptal requested changes
Obrigado pela contribuição! Adicionei alguns comentários para você dar uma olhada.

2021-03-08 14:12 UTC, lucastfa-toptal commented on pages/core-concepts/interacting-with-elements.md
> +Ao usar o [`Log de comandos`](https://docs.cypress.io/guides/core-concepts/test-runner.html#Command-Log) para passar o
Me parece que esse já existe, está na linha 191 :P basta mover ele pra acima da linha do link.

2021-03-08 14:12 UTC, lucastfa-toptal commented on pages/core-concepts/interacting-with-elements.md
> +O motivo pelo qual rolamos um elemento para exibição ao passar o mouse sobre um instantâneo é para ajudá-lo a ver quais
"passar o mouse sobre um instantâneo" me soa um pouco sem sentido. A tradução de snapshot seria um determinado estado/passo do teste em questão quando estava sendo executado. Uma fotografia daquele ponto específico. Que tal "ao passar o mouse sobre um comando executado". Faz mais sentido do que a tradução literal nesse caso.

2021-03-08 14:12 UTC, lucastfa-toptal commented on pages/core-concepts/interacting-with-elements.md
> +Em outras palavras, você não pode obter uma representação visual correta do que Cypress “viu” ao olhar para um
Mesma situação, "olhar para um instantâneo" anterior não tem muito sentido.

2021-03-08 15:53 UTC, lucastfa-toptal approved these changes

2021-03-09 03:00 UTC, pedrohyvo requested changes
@murillowelsi antes de fazer o merge só precisa fazer esses pequenos ajustes que você deve ter esquecido, após isso, já pode solicitar uma pagina lá na issue #22 . 🍰 🚀

2021-03-09 03:00 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +(descrito em detalhes no guia de conceito principal [`Default Assertions`](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Default-Assertions)).
Falta colocar TODO acima desse bloco de texto.

2021-03-09 03:00 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +interagir. Você sempre pode [`aumentar ou diminuir esse limite`](https://docs.cypress.io/guides/references/configuration.html#Actionability).
@murillowelsi acho que você esqueceu desse TODO aqui

2021-03-09 03:00 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +Você também pode desligar nossas verificações de animações com a opção de configuração [`waitForAnimations`](https://docs.cypress.io/guides/references/configuration.html#Actionability).
@murillowelsi aqui também

2021-03-09 03:00 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +acima. Nós *não* rolamos elementos com os comandos DOM regulares como `cy.get()` ou `.find()`.
@murillowelsi opa, faltou fazer esse link aqui

2021-03-10 11:51 UTC, pedrohyvo commented
@murillowelsi desculpa cara, mas passou despercebido que falta você adicionar a página na lista de conteúdo no arquivo README, beleza?

2021-03-10 16:58 UTC, murillowelsi commented
@pedrohyvo sem problemas (: ...
correção feita! aproveitei para adicionar a página "Introdução ao Cypress" também, pois não estava no README.

2021-03-11 00:17 UTC, pedrohyvo requested changes
Falta apenas ajustar os links na seção "Verificações e Ações Realizadas"

2021-03-11 00:17 UTC, pedrohyvo commented on pages/core-concepts/interacting-with-elements.md
> +- [`Disparar o evento nas coordenadas desejadas.`](##coordenadas)
@murillowelsi nenhum dos links está funcionando. Você poderia fazer essa última alteração, por favor

2021-03-11 00:48 UTC, murillowelsi commented on pages/core-concepts/interacting-with-elements.md
> +- [`Disparar o evento nas coordenadas desejadas.`](##coordenadas)
opa, my bad...corrigi e agora parece estar ok

2021-03-11 01:00 UTC, pedrohyvo commented
@all-contributors please add @murillowelsi  for code

2021-03-11 01:00 UTC, merged

2021-03-11 01:01 UTC, pedrohyvo commented
@murillowelsi parabéns mano! Já pode pegar outra página quando você quiser 🚀