Tooling typescript
pedrohyvo/cypress-docs-pt-br pull request #60
Opened 2021-03-10 23:01 UTC by driuzzo

@pedrohyvo finalizei a página Tooling, seção TypeScript. Sugestões de alteração na tradução são bem-vindas. Lembrando que alguns links ainda precisam ser atualizados, pois são da documentação original.

2021-03-11 00:36 UTC, pedrohyvo requested changes
Ao finalizar todas as requested changes, não esquecer de resolver as issues e também manter a branch da master atualizada. Após finalizar tudo, não esquece de adicionar a página na tabela de conteúdo no README também, seguindo a estrutura de páginas na doc oficial. Excelente trabalho e parabéns pela primeira contribuição! 🍰 🚀

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +para [TypeScript](https://www.typescriptlang.org/). Isso permite que você escreva seus testes em TypeScript.
Precisar adicionar a linha TODO antes de cada bloco de texto que tenha links que precisam ser atualizados.

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +Encontre o seu editor de código no
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +Recomendamos a seguinte configuração em um arquivo
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +O `"types"` informa para o compilador TypeScript incluir apenas definições de tipo do Cypress. Ao fazer isso,
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +Então você pode adicionar o comando `dataCy` na interface global Chainable do Cypress (chamada assim pois os comandos
aqui que você esqueceu de traduzir algo aqui, não?

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +Então você pode adicionar o comando `dataCy` na interface global Chainable do Cypress (chamada assim pois os comandos
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +[`supportFile`](https://docs.cypress.io/guides/references/configuration.html#Folders-Files) assim:
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +separado no repositório [cyperss-io/cypress-and-jest-typescript-example](https://github.com/cypress-io/cypress-and-jest-typescript-example).
precisa ajustar o nome cypress-io

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +são namespaces (globais), versões incompatíveis farão o gerenciador de pacotes (yarn ou npm) juntar e incluir
acha que teria alguma tradução para substituir namespace ou não?

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +- [Integração do IDE](https://docs.cypress.io/guides/tooling/IDE-integration.html)
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +| Versão | Mudanças                                                                                                   |
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +[arquivo de plugins](https://docs.cypress.io/guides/tooling/plugins-guide.html#Use-Cases) anotando da seguinte forma:
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +[Receita: Adicionando Asserções Chai](https://docs.cypress.io/examples/examples/recipes.html#Fundamentals)
Adicionar linha TODO aqui também

2021-03-11 00:36 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +- Veja a receita de exemplo em [Adicionando Comandos Personalizados](https://github.com/cypress-io/cypress-example-recipes#fundamentals).
Adicionar linha TODO aqui também

2021-03-11 23:37 UTC, driuzzo commented on pages/tooling/typescript.md
> +Então você pode adicionar o comando `dataCy` na interface global Chainable do Cypress (chamada assim pois os comandos
Aqui nesse caso o nome da interface é Chainable mesmo. Acha melhor traduzir?

2021-03-12 20:51 UTC, driuzzo commented on pages/tooling/typescript.md
> +separado no repositório [cyperss-io/cypress-and-jest-typescript-example](https://github.com/cypress-io/cypress-and-jest-typescript-example).
Ajustado

2021-03-12 20:52 UTC, driuzzo commented on pages/tooling/typescript.md
> +são namespaces (globais), versões incompatíveis farão o gerenciador de pacotes (yarn ou npm) juntar e incluir
Na verdade eu sempre vejo falarem namespace mesmo no Brasil. Como acha melhor: Conjunto de nomes? Espaço de nomes?

2021-03-12 21:03 UTC, driuzzo commented on pages/tooling/typescript.md
> +para [TypeScript](https://www.typescriptlang.org/). Isso permite que você escreva seus testes em TypeScript.
Feito!

2021-03-12 21:03 UTC, driuzzo commented on pages/tooling/typescript.md
> +Encontre o seu editor de código no
Feito!

2021-03-12 21:03 UTC, driuzzo commented on pages/tooling/typescript.md
> +Recomendamos a seguinte configuração em um arquivo
Feito!

2021-03-12 21:03 UTC, driuzzo commented on pages/tooling/typescript.md
> +O `"types"` informa para o compilador TypeScript incluir apenas definições de tipo do Cypress. Ao fazer isso,
Feito!

2021-03-12 21:03 UTC, driuzzo commented on pages/tooling/typescript.md
> +Então você pode adicionar o comando `dataCy` na interface global Chainable do Cypress (chamada assim pois os comandos
Feito!

2021-03-12 21:03 UTC, driuzzo commented on pages/tooling/typescript.md
> +[`supportFile`](https://docs.cypress.io/guides/references/configuration.html#Folders-Files) assim:
Feito!

2021-03-12 21:04 UTC, driuzzo commented on pages/tooling/typescript.md
> +- [Integração do IDE](https://docs.cypress.io/guides/tooling/IDE-integration.html)
Feito!

2021-03-12 21:04 UTC, driuzzo commented on pages/tooling/typescript.md
> +| Versão | Mudanças                                                                                                   |
Feito!

2021-03-12 21:04 UTC, driuzzo commented on pages/tooling/typescript.md
> +[arquivo de plugins](https://docs.cypress.io/guides/tooling/plugins-guide.html#Use-Cases) anotando da seguinte forma:
Feito!

2021-03-12 21:04 UTC, driuzzo commented on pages/tooling/typescript.md
> +[Receita: Adicionando Asserções Chai](https://docs.cypress.io/examples/examples/recipes.html#Fundamentals)
Feito!

2021-03-12 21:04 UTC, driuzzo commented on pages/tooling/typescript.md
> +- Veja a receita de exemplo em [Adicionando Comandos Personalizados](https://github.com/cypress-io/cypress-example-recipes#fundamentals).
Feito!

2021-03-13 04:58 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +são namespaces (globais), versões incompatíveis farão o gerenciador de pacotes (yarn ou npm) juntar e incluir
@driuzzo verdade cara, pensando bem acredito que seja melhor deixarmos namespaces mesmo. Beleza? O que você acha @lucastfa-toptal ?

2021-03-18 21:43 UTC, driuzzo commented on pages/tooling/typescript.md
> +são namespaces (globais), versões incompatíveis farão o gerenciador de pacotes (yarn ou npm) juntar e incluir
@pedrohyvo ae cara, só avisando que estou aguardando o fechamento desse apontamento para eu subir os itens resolvidos. Beleza?

2021-03-18 21:51 UTC, pedrohyvo commented on pages/tooling/typescript.md
> +são namespaces (globais), versões incompatíveis farão o gerenciador de pacotes (yarn ou npm) juntar e incluir
@driuzzo pode deixar do jeito que está e submeter as mudanças ;)

2021-03-18 22:11 UTC, driuzzo reviewed
Apontamentos resolvidos. @pedrohyvo não tenho muita experiência em pull request, você consegue validar se tá tudo certo da minha parte ou se preciso fazer mais alguma coisa?

2021-03-19 03:35 UTC, pedrohyvo commented
@driuzzo parabéns pela contribuição cara, faltou apenas adicionar a sua página na tabela de conteúdo no README. Fazendo isso já aprovo seu PR e te adiciono a lista de contribuidores 😄 🚀

2021-03-19 13:06 UTC, driuzzo commented
> @driuzzo parabéns pela contribuição cara, faltou apenas adicionar a sua página na tabela de conteúdo no README. Fazendo isso já aprovo seu PR e te adiciono a lista de contribuidores 😄 🚀

2021-03-19 13:09 UTC, driuzzo commented
@pedrohyvo valeu pelas palavras! Adicionei a página no README, acredito que agora esteja ok! Se eu tiver tempo, vou pegar mais alguma página! Obrigado!

2021-03-23 01:15 UTC, pedrohyvo commented
@all-contributors please add @driuzzo for code

2021-03-23 01:15 UTC, merged