Variables and aliases core concepts
pedrohyvo/cypress-docs-pt-br pull request #63
Opened 2021-03-14 11:37 UTC by murillowelsi

Finished doc: Variable and Aliases page

2021-03-23 23:54 UTC, pedrohyvo requested changes
Excelente contribuição @murillowelsi !!! Parabéns cara, muito bom mesmo. Deixei apenas alguns comentários simples, antes de fazer o merge. 🍰 🚀 🚀

2021-03-23 23:54 UTC, pedrohyvo commented on pages/core-concepts/variables-and-aliases.md
> +- Por que você raramente precisa usar variáveis com Cypress
```suggestion
- Por que você raramente precisa usar variáveis com o Cypress
```

2021-03-23 23:54 UTC, pedrohyvo commented on pages/core-concepts/variables-and-aliases.md
> +Apelidos também podem ser usados com [requisições](https://docs.cypress.io/api/commands/request.html).
Falta adicionar linha TODO aqui

2021-03-23 23:54 UTC, pedrohyvo commented on pages/core-concepts/variables-and-aliases.md
> +> [Temos um guia muito mais detalhado e abrangente sobre o roteamento de requisições de rede.](https://docs.cypress.io/guides/guides/network-requests.html)
Falta adicionar linha TODO aqui

2021-03-24 21:35 UTC, murillowelsi commented
Correções feitas @pedrohyvo , obrigado pelas observações (:

2021-03-26 22:51 UTC, pedrohyvo approved these changes
Bom trabalho @murillowelsi !!! Muito obrigado por mais uma contribuição cara 🚀 🚀

2021-03-26 22:51 UTC, merged