Dashboard gitlab integration
pedrohyvo/cypress-docs-pt-br pull request #67
Opened 2021-04-07 21:59 UTC by driuzzo

2021-04-14 12:31 UTC, pedrohyvo requested changes
@driuzzo você esqueceu de adicionar a página a Tabela de Conteúdo no README e adicionei apenas um comentário, o restante está ok. Parabéns por mais uma contribuição! 🚀 🍰

2021-04-14 12:31 UTC, pedrohyvo commented on pages/dashboard/gitlab-integration.md
> +5. (Opicional) Configure o comportamento para cada projeto.
```suggestion
5. (Opcional) Configure o comportamento para cada projeto.
```

2021-04-14 12:32 UTC, pedrohyvo commented on pages/dashboard/gitlab-integration.md
> +Tem ideias sobre como podemos melhorar nossa Integração com o GitLab? [Conte-nos!](https://portal.productboard.com/cypress-io/1-cypress-dashboard/c/48-gitlab-integration?utm_medium=social&utm_source=
Acho que ao final do documento, você poderia adicionar Voltar para o topo? só pra manter o padrão mesmo :)

2021-04-14 14:48 UTC, driuzzo commented on pages/dashboard/gitlab-integration.md
> +Tem ideias sobre como podemos melhorar nossa Integração com o GitLab? [Conte-nos!](https://portal.productboard.com/cypress-io/1-cypress-dashboard/c/48-gitlab-integration?utm_medium=social&utm_source=
Boa Pedro! Adicionei lá.

2021-05-03 21:22 UTC, pedrohyvo approved these changes
Good to go! 🥳 🚀

2021-05-03 21:23 UTC, merged