Finished "Introduction to Cypress - Assertions"
pedrohyvo/cypress-docs-pt-br pull request #68
Opened 2021-05-01 20:03 UTC by edmundobiglia

https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Assertions

2021-05-03 22:10 UTC, pedrohyvo requested changes
@edmundobiglia deixei alguns comentários e o restante está ok

2021-05-03 22:10 UTC, pedrohyvo commented on pages/core-concepts/introduction-to-cypress.md
> +Como [`.should('have.class')`](https://docs.cypress.io/api/commands/should)
Adicionar TODO aqui acima

2021-05-03 22:10 UTC, pedrohyvo commented on pages/core-concepts/introduction-to-cypress.md
> +> isso significa que seu código deve ser **idempotente**.
**idempotente**. acho que precisa ajustar isso aqui

2021-05-03 22:11 UTC, pedrohyvo commented on pages/core-concepts/introduction-to-cypress.md
>  $('.my-selector')
Falta adicionar a página no README

2021-05-03 23:22 UTC, edmundobiglia commented on pages/core-concepts/introduction-to-cypress.md
> +> isso significa que seu código deve ser **idempotente**.
@pedrohyvo você acha melhor usar outra palavra em vez de idempotente, é isso?

2021-05-04 01:12 UTC, pedrohyvo commented on README.md
> +    - [Introdução ao Cypress](pages/core-concepts/writing-and-organizing-tests.md)
@edmundobiglia você colocou na seção errada, ele deve estar na seção de "Conceitos Principais" que é a tradução de "Core Concepts" seguindo a documentação oficial, entende?

2021-05-04 01:17 UTC, edmundobiglia commented on README.md
> +    - [Introdução ao Cypress](pages/core-concepts/writing-and-organizing-tests.md)
@pedrohyvo desculpe! Já corrigi.

2021-05-04 01:19 UTC, pedrohyvo approved these changes
Excelente @edmundobiglia !!! Parabéns pela contribuição

2021-05-04 01:20 UTC, merged