Debugging guides
pedrohyvo/cypress-docs-pt-br pull request #69
Opened 2021-07-21 23:27 UTC by camillamsantos

Segue pull request da tradução de Pages/Guides/Debugging.

2021-07-22 01:36 UTC, pedrohyvo requested changes
@camillamsantos coloquei alguns comentários, mas a sua contribuição está excelente! Parabéns!!!! 🍰

2021-07-22 01:36 UTC, pedrohyvo commented on pages/guides/debugging.md
> +- Como e quando usar debugger e o [`.debug()`](https://docs.cypress.io/api/commands/debug)
```suggestion
```markdown
O que você vai aprender

- Como o Cypress é executado no mesmo loop de evento com seu código, mantendo a depuração menos exigente e mais compreensível
- Como o Cypress adota as ferramentas de desenvolvedor padrão
- Como e quando usar debugger e o [`.debug()`](https://docs.cypress.io/api/commands/debug)
```

2021-07-22 01:36 UTC, pedrohyvo commented on pages/guides/debugging.md
> +Ambos [`cy.visit()`](https://docs.cypress.io/api/commands/visit)e [`cy.get()`](https://docs.cypress.io/api/commands/get) retornarão imediatamente, tendo enfileirado seu trabalho para ser feito mais t
Faltou colocar um espaço depois da url cy.visit

2021-07-22 01:36 UTC, pedrohyvo commented on pages/guides/debugging.md
> +7 - **Botão Imprimir no console** : Clique aqui para imprimir o erro completo no console do DevTools. Isso geralmente permitirá que você clique em linhas no rastreamento de pilha e abra arquivos em s
Está faltando uma imagem logo abaixo do item 7 de acordo com a documentação oficial

2021-07-22 01:36 UTC, pedrohyvo commented on pages/guides/debugging.md
> +Enquanto estiver aprendendo o Cypress, pode ser uma boa ideia tentar pequenos testes em HTML. Nós escrevemos um plugin [`@ cypress/fiddle `](https://github.com/cypress-io/cypress-fiddle)para isso. El
tem um espaço depois do @ que acho que não deveria existir, certo?

2021-07-22 01:36 UTC, pedrohyvo commented on pages/guides/debugging.md
> +Enquanto estiver aprendendo o Cypress, pode ser uma boa ideia tentar pequenos testes em HTML. Nós escrevemos um plugin [`@ cypress/fiddle `](https://github.com/cypress-io/cypress-fiddle)para isso. El
Colocar um espaço depois do link do cypress/fiddle antes do 'para isso'

2021-07-22 01:36 UTC, pedrohyvo commented on pages/guides/debugging.md
> +- [`Não se desvie demais`](https://www.cypress.io/blog/2020/07/22/do-not-get-too-detached/)
Ao final de toda página traduzida a gente sempre coloca o link de Voltar para o topo:

[Voltar para o topo](#nome-da-pagina)

2021-07-22 01:36 UTC, pedrohyvo commented on pages/guides/debugging.md
> +3 - A função passada para [`.then()`](https://docs.cypress.io/api/commands/then) é executada, com o elemento encontrado atribuido a ela.
Para todos os links que não possuem tradução ainda, colocamos a seguinte linha acima do texto:

ex:
[//]: <> (TODO - Adicionar links cy.visit e .click() quando traduzidos)

Para que possamos futuramente revisitar esses lugares e atualizar para das páginas traduzidas, tá?

2021-07-22 01:38 UTC, pedrohyvo commented on pages/guides/debugging.md
> +3 - A função passada para [`.then()`](https://docs.cypress.io/api/commands/then) é executada, com o elemento encontrado atribuido a ela.
Você também precisa atualizar o README com a sua página

2021-07-22 02:44 UTC, camillamsantos commented on pages/guides/debugging.md
> +- Como e quando usar debugger e o [`.debug()`](https://docs.cypress.io/api/commands/debug)
adicionei o trecho de ```markdown, e após os ``` no final do bloco.. commitei a alteração, porém o link do .debug não é mais exibido corretamente

![image](https://user-images.githubusercontent.com/84816792/126583344-3fe5833b-e4dd-45c3-aa7c-fe9e8e50e4d7.png)

2021-07-22 02:46 UTC, camillamsantos commented on pages/guides/debugging.md
> +Ambos [`cy.visit()`](https://docs.cypress.io/api/commands/visit)e [`cy.get()`](https://docs.cypress.io/api/commands/get) retornarão imediatamente, tendo enfileirado seu trabalho para ser feito mais t
ajustado.

2021-07-22 02:48 UTC, camillamsantos commented on pages/guides/debugging.md
> +7 - **Botão Imprimir no console** : Clique aqui para imprimir o erro completo no console do DevTools. Isso geralmente permitirá que você clique em linhas no rastreamento de pilha e abra arquivos em s
ajustado.

2021-07-22 02:50 UTC, camillamsantos commented on pages/guides/debugging.md
> +Enquanto estiver aprendendo o Cypress, pode ser uma boa ideia tentar pequenos testes em HTML. Nós escrevemos um plugin [`@ cypress/fiddle `](https://github.com/cypress-io/cypress-fiddle)para isso. El
ajustado.

2021-07-22 02:51 UTC, camillamsantos commented on pages/guides/debugging.md
> +Enquanto estiver aprendendo o Cypress, pode ser uma boa ideia tentar pequenos testes em HTML. Nós escrevemos um plugin [`@ cypress/fiddle `](https://github.com/cypress-io/cypress-fiddle)para isso. El
ajustado

2021-07-22 02:54 UTC, camillamsantos commented on pages/guides/debugging.md
> +- [`Não se desvie demais`](https://www.cypress.io/blog/2020/07/22/do-not-get-too-detached/)
ajustado

2021-07-22 03:23 UTC, camillamsantos commented on pages/guides/debugging.md
> +3 - A função passada para [`.then()`](https://docs.cypress.io/api/commands/then) é executada, com o elemento encontrado atribuido a ela.
ajustei o README e também os links que ainda não tem tradução com o [//]: <> (TODO - Adicionar links cy.visit e .click() quando traduzidos) conforme orientado.


Uma dúvida.. eu preciso enviar um pull request novamente, ou as alterações que fiz já aparecem pra ti?

Sou nova nisso..

2021-07-22 03:24 UTC, camillamsantos commented
> @camillamsantos coloquei alguns comentários, mas a sua contribuição está excelente! Parabéns!!!! 🍰

Obrigada :)

2021-07-28 18:34 UTC, pedrohyvo commented
@camillamsantos o seu PR tem alguns problemas com o markdown-lint, eu recomendo você rodar esse comando localmente e tentar corrigir os problemas reportados no seu console. Dá uma olhada nesse link aqui - https://github.com/pedrohyvo/cypress-docs-pt-br/blob/master/CONTRIBUTING.md#como-rodar-o-markdown-lint-localmente . Qualquer coisa, me chama no Telegram que posso tentar te ajudar por lá, tá?

2021-10-04 21:09 UTC, pedrohyvo commented
Tried to contact you to complete this translation with no success, let me know when you want to contribute again for this project. We'll be glad to have you here again

2021-10-04 21:09 UTC, closed without merging