Update installing-cypress.md
pedrohyvo/cypress-docs-pt-br pull request #70
Opened 2021-07-26 19:01 UTC by samlucax

Updating some important pre-reqs like Node version

2021-07-26 19:57 UTC, wlsf82 requested changes
Obrigado pela contribuição!
Creio que com os ajustes sugeridos podemos tê-lo aprovado.
🚀

2021-07-26 19:57 UTC, wlsf82 commented on pages/getting-started/installing-cypress.md
> +        # if targeting a specific node version, use e.g.
Que tal traduzir os comentários?

2021-07-26 19:57 UTC, wlsf82 commented on pages/getting-started/installing-cypress.md
> +cd /your/project/path
Qual motivo de substituir a tradução pela versão em inglês?

2021-07-26 19:57 UTC, wlsf82 commented on pages/getting-started/installing-cypress.md
> +<strong class="alert-header">Direct downloading for old versions</strong>
Que tal traduzir o content dessa tag strong?

2021-07-26 21:28 UTC, wlsf82 approved these changes
:cake:

Obrigado pela contribuição @samlucax!

2021-07-26 21:32 UTC, wlsf82 commented
@pedrohyvo, que tipe de estratégia de merge usamos? Merge pull request ou Rebase and merge?

2021-07-27 19:18 UTC, merged

2021-07-28 13:25 UTC, pedrohyvo commented
@all-contributors please add @samlucax for code