adicionada pagina test retries
pedrohyvo/cypress-docs-pt-br pull request #72
Opened 2021-08-01 02:43 UTC by mhanelia

@pedrohyvo adicionei a página de test retries, fiquei na dúvida em relação a um vídeo que tem na página oficial do Cypress e acabei deixando como um link (linha 257)

2021-08-03 17:07 UTC, pedrohyvo requested changes
@mhanelia parabéns pela contribuição!! Coloquei alguns comentários no seu PR que são bem simples, mas o restante está ok. 🚀

2021-08-03 17:07 UTC, pedrohyvo commented on pages/guides/test-retries.md
> +[configuração do teste](../core-concepts/writing-and-organizing-tests.md#Configuração-de-Teste)
não ficaria melhor configuraçÃO de teste?

2021-08-03 17:07 UTC, pedrohyvo commented on pages/guides/test-retries.md
> +[cy.screenshot()](https://docs.cypress.io/api/commands/screenshot) com sufixo a nova captura de tela com `(attempt n)`,
Falta adicionar TODO para cy.screenshot()

2021-08-03 17:07 UTC, pedrohyvo commented on pages/guides/test-retries.md
> +[Flake Alerting](https://docs.cypress.io/guides/dashboard/flaky-test-management#Flake-Alerting)
Falta adicionar linha TODO para os linsk Flaky

2021-08-03 17:07 UTC, pedrohyvo commented on pages/guides/test-retries.md
> +````
Falta adicionar o link Voltar para o Topo ao final da página

2021-08-08 21:45 UTC, mhanelia commented
@pedrohyvo realizei as alterações, devo criar um novo PR?

2021-08-09 13:17 UTC, pedrohyvo commented
@all-contributors please add @mhanelia for code

2021-08-09 13:18 UTC, pedrohyvo commented
@mhanelia obrigado pela contribuição! Fique a vontade para pegar outra página na issue aberta lá, essa vai ser atualizada também! 🚀

2021-08-09 13:18 UTC, pedrohyvo approved these changes

2021-08-09 13:19 UTC, merged