Tradução da GitHub Integration
pedrohyvo/cypress-docs-pt-br pull request #73
Opened 2021-08-03 07:10 UTC by wellmalta

2021-08-09 13:24 UTC, pedrohyvo requested changes
@wellmalta Muito obrigado pela contribução!!! O seu PR está quase pronto, pedi somente alguns ajustes simples e já está praticamente pronto para fazer o merge, bom trabalho!

2021-08-09 13:24 UTC, pedrohyvo commented on pages/dashboard/github-integration.md
> +Um projeto inicialmente precisa estar [configurado para gravação](https://docs.cypress.io/guides/dashboard/projects)
Precisa adicionar linha TODO acima do texto para atualizar o link quando a página for traduzida.

2021-08-09 13:24 UTC, pedrohyvo commented on pages/dashboard/github-integration.md
> +seguindo [essas diretrizes](https://docs.cypress.io/guides/continuous-integration/introduction#Git-information).
Precisa adicionar linha TODO acima do texto para atualizar o link quando a página for traduzida.

2021-08-09 13:24 UTC, pedrohyvo commented on pages/dashboard/github-integration.md
> +5. Clique no botão **Instalar Cypress GitHub App**.
O ideal seria você traduzir apenas o texto e deixar o nome de abas, botões ou elementos do Cypress Dashboard em inglês mesmo para o pessoal não se confudir quando for reproduzir.

2021-08-09 13:24 UTC, pedrohyvo commented on pages/dashboard/github-integration.md
> +1. CLique em **desinstalar** abaixo da seção "desinstalar Cypress".
Corrigir listagem numérica e atualizar o nome dos botões e/ou páginas para inglês.
Exemplo: Clique na aba "Configuration" para visualizar as configurações do teste.

2021-08-20 08:26 UTC, wellmalta commented
Et voilà! creio que corrigi o que foi pedido, ficarei atento para alguma possível correção @pedrohyvo

2021-09-28 19:45 UTC, pedrohyvo approved these changes

2021-09-28 19:45 UTC, merged

2021-09-28 19:52 UTC, pedrohyvo commented
@all-contributors please add @wellmalta for code