add Cypress studio page
pedrohyvo/cypress-docs-pt-br pull request #74
Opened 2021-08-04 02:22 UTC by fsreibnitz

Adição da página com sua tradução

2021-08-11 02:20 UTC, pedrohyvo requested changes
@fsreibnitz primeiramente, muito obrigado pela contribuição, a página está excelente!! 🚀 
Adicionei alguns pequenos ajustes que devem ser corrigidos antes que possamos fazer o merge do seu PR, tá bem? Qualquer coisa, só me procurar ;)

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +# Cypress Studio
Você precisa adicionar essa página traduzida no README

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +Cypress Studio fornece uma maneira visual de gerar testes dentro do Test Runner, gravando interações com o aplicação em teste.
"O Cypress Studio.."

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +Os comandos [`.click()`](https://docs.cypress.io/api/commands/click.html), [`.type()`](https://docs.cypress.io/api/commands/type.html), [`.check()`](https://docs.cypress.io/api/commands/check.html),
Colocar linha TODO acima do bloco de texto para quando as páginas forem traduzidas, os links devem ser atualizados.

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +Cypress Studio é uma funcionalidade experimental e pode ser habilitada adicionando o atributo [`experimentalStudio`](https://docs.cypress.io/guides/references/experiments) no seu arquivo de configura
Colocar linha TODO acima do bloco de texto para quando as páginas forem traduzidas, os links devem ser atualizados.

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +Cypress Studio é uma funcionalidade experimental e pode ser habilitada adicionando o atributo [`experimentalStudio`](https://docs.cypress.io/guides/references/experiments) no seu arquivo de configura
Ajustar "O Cypress Studio.."

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +Voce pode estender qualquer teste preexistente ou começar criando um novo teste no seu [`integrationFolder`](https://docs.cypress.io/guides/references/configuration#Folders-Files) (`cypress/integrati
Colocar linha TODO acima do bloco de texto para quando as páginas forem traduzidas, os links devem ser atualizados.

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +Cypress Studio é diretamente integrado com o [`Log de Comando`](https://docs.cypress.io/guides/core-concepts/test-runner#Command-Log)
Colocar linha TODO acima do bloco de texto para quando as páginas forem traduzidas, os links devem ser atualizados.

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +Para descartar as interações, clique no botão "Cancelar" para sair do Cypress Studio. Se estiver satisfeito com as interações com a aplicação, clique em "Save commands" e o código de teste será salvo
O ideal seria você utilizar os nomes em inglês, caso você for referenciar a alguma tela do Cypress Studio, no caso seria: clique no botão "Cancel", entende?

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +atualizado depois após clickar em "Save Commands" com as ações que gravamos no Cypress Studio.
Corrigir a palavra clicar

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +| 6.3.0  | Adicionado Cypress Studio como experimental |
Falta adicionar botão Voltar para o topo

2021-08-11 02:20 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +| Versão |                   Mudanças                  |
Corrigir todos as issues do lint, no nosso guia de como contributir tem uma forma de como rodar o lint e você pode corrigir todas as issues para que seu PR seja revisado novamente

2021-08-12 01:32 UTC, fsreibnitz commented on pages/core-concepts/cypress-studio.md
> +| 6.3.0  | Adicionado Cypress Studio como experimental |
esse botão não tem na versão original..

2021-08-12 01:33 UTC, fsreibnitz commented on pages/core-concepts/cypress-studio.md
> +| Versão |                   Mudanças                  |
vou tentar aqui, eu tinha dado uma olhada mas achei que não estava correto mesmo

2021-08-12 02:02 UTC, fsreibnitz commented
> @fsreibnitz primeiramente, muito obrigado pela contribuição, a página está excelente!! 
> Adicionei alguns pequenos ajustes que devem ser corrigidos antes que possamos fazer o merge do seu PR, tá bem? Qualquer coisa, só me procurar ;)

Valeu Pedro, espero que de certo agora, senão preciso de ajuda de como configurar o lint 🙄

2021-08-12 02:44 UTC, pedrohyvo requested changes
@fsreibnitz deixei apenas um comentário, depois disso faço o merge ;)

2021-08-12 02:44 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +  1. Clique no botão "Save"
@fsreibnitz precisa ajustar apenas a ordenação aqui que ficou todos os pontos sendo 1, o restante tá ok cara, muito bom mesmo!

2021-08-12 02:44 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +Para discartar as interações, clique no botão "Cancel" para sair do Cypress Studio.
Para descartar*

2021-08-12 18:15 UTC, fsreibnitz commented on pages/core-concepts/cypress-studio.md
> +  1. Clique no botão "Save"
então, aqui foi o lint que não deixou outra ordenação.. tive que deixar assim pra passar.. mas achei que podia ser algo que ele iria corrigir depois..

2021-08-12 18:35 UTC, pedrohyvo commented
@all-contributors please add @fsreibnitz for code

2021-08-12 18:35 UTC, fsreibnitz commented on pages/core-concepts/cypress-studio.md
> +  1. Clique no botão "Save"
entendi porque dava erro.. era por causa da identação do texto que vinha após o  número da lista

2021-08-12 18:37 UTC, pedrohyvo commented on pages/core-concepts/cypress-studio.md
> +| 6.3.0  | Adicionado Cypress Studio como experimental |
@fsreibnitz é um padrão nosso em todas as páginas :)

2021-08-12 18:38 UTC, pedrohyvo approved these changes
@fsreibnitz parabéns pela contribuição amigo! 🚀 Se quiser pegar outra página para traduzir basta mencionar lá na issue ;)

2021-08-12 18:38 UTC, merged

2021-08-12 18:51 UTC, fsreibnitz commented
> @fsreibnitz parabéns pela contribuição amigo!  Se quiser pegar outra página para traduzir basta mencionar lá na issue ;)

Obrigado colega, darei uma olhada depois 👍🏻 
parabéns a todos pelo trabalho