Module API guides
pedrohyvo/cypress-docs-pt-br pull request #77
Opened 2021-09-04 02:40 UTC by Wil-g2

Segue pull request da tradução de Pages/Guides/Module-API.

2021-09-06 13:16 UTC, wlsf82 commented on pages/guides/module-api.md
> +Com este fluxo de trabalho, por exemplo, você pode:
Que tal

```suggestion
Com este fluxo de trabalho voce pode, por exemplo:
```

2021-09-06 13:16 UTC, wlsf82 commented on pages/guides/module-api.md
> +- Envie uma notificação sobre testes com falha com imagens de captura de tela incluídas
```suggestion
- Enviar uma notificação sobre testes com falha com imagens de captura de tela incluídas
```

2021-09-06 13:16 UTC, wlsf82 commented on pages/guides/module-api.md
> +- Execute novamente um único arquivo de especificação com falha
```suggestion
- Executar novamente um único arquivo de especificação com falha
```

2021-09-06 13:16 UTC, wlsf82 commented on pages/guides/module-api.md
> +- Dê início a outras compilações ou scripts
```suggestion
- Dar início a outras compilações ou scripts
```

2021-09-06 13:17 UTC, wlsf82 commented on pages/guides/module-api.md
> +Executa testes do Cypress via Node.js e resolve com todos os resultados de teste. Veja o [Cypress Módulo API recipe](https://github.com/cypress-io/cypress-example-recipes#fundamentals).
```suggestion
Executa testes do Cypress via Node.js e resolve com todos os resultados de teste. Veja a receita do [Cypress Módulo API](https://github.com/cypress-io/cypress-example-recipes#fundamentals).
```

2021-09-06 13:18 UTC, wlsf82 commented on pages/guides/module-api.md
> +Você pode então executar o Cypress executando o seguinte em seu terminal ou um script npm:
Executar executando ficou estranho.

Que tal:

```suggestion
Você pode então rodar o Cypress executando o seguinte em seu terminal ou em um script npm:
```

2021-09-06 13:20 UTC, wlsf82 commented on pages/guides/module-api.md
> +|     headed      |     boolean      | Exibe o navegador em vez de funcionar sem controle
```suggestion
|     headed      |     boolean      | Executa no navegador em vez do modo _headless_                                                                                                                                                                                      |
```

2021-09-06 13:21 UTC, wlsf82 commented on pages/guides/module-api.md
> +|    headless     |     boolean      | Oculte o navegador em vez de executar o cabeçalho (padrão durante a execução do cipreste)
```suggestion
|    headless     |     boolean      | Oculte o navegador em vez de executar em modo _headed_ (padrão durante a execução do Cypress)                                                                                                                                               |
```

2021-09-06 13:22 UTC, wlsf82 commented on pages/guides/module-api.md
> +|      quiet      |     boolean      | Se aprovado, a saída do Cypress não será impressa no stdout. Apenas a saída do [repórter Mocha](https://docs.cypress.io/guides/tooling/reporters) configurado se
```suggestion
|      quiet      |     boolean      | Se aprovado, a saída do Cypress não será impressa no stdout. Apenas a saída do [relatório Mocha](https://docs.cypress.io/guides/tooling/reporters) configurado será impressa.                                                            |
```

2021-09-06 13:23 UTC, wlsf82 commented on pages/guides/module-api.md
> +|    reporter     |      string      | Especifica um repórter Mocha
```suggestion
|    reporter     |      string      | Especifica um relatório Mocha                                                                                                                                                                                                            |
```

2021-09-06 13:23 UTC, wlsf82 commented on pages/guides/module-api.md
> +| reporterOptions |      object      | Especifica as opções do repórter Mocha
```suggestion
| reporterOptions |      object      | Especifica as opções do relatório Mocha                                                                                                                                                                                                  |
```

2021-09-06 13:24 UTC, wlsf82 commented on pages/guides/module-api.md
> +|      spec       |      string      | Especifica as especificações a serem executadas, consulte os exemplos abaixo
Especifica as especificações fica estranho.

Que tal:

```suggestion
|      spec       |      string      | Especifica os arquivos de teste a serem executados, consulte os exemplos abaixo                                                                                                                                                            |
```

2021-09-06 13:24 UTC, wlsf82 commented on pages/guides/module-api.md
> +|   testingType   |      string      | Especifica o tipo de testes a serem executados ou e2e ou componente. Padrões para e2e
```suggestion
|   testingType   |      string      | Especifica os tipos de testes a serem executados, ou e2e ou componente. Padrões para e2e                                                                                                                                                  |
```

2021-09-06 13:25 UTC, wlsf82 commented on pages/guides/module-api.md
> +Você pode então executar o Cypress executando o seguinte em seu terminal ou um script npm:
```suggestion
Você pode então rodar o Cypress executando o seguinte em seu terminal ou um script npm:
```

2021-09-06 13:27 UTC, wlsf82 commented on pages/guides/module-api.md
> +Você pode encontrar a definição do TypeScript para o objeto de resultados no [cypress/cli/pastas de tipos](https://github.com/cypress-io/cypress/tree/develop/cli/types).
no [cypress/cli/pastas de tipos]?

Ficou estranho isso. Sugiro revisar.

2021-09-06 13:29 UTC, wlsf82 commented on pages/guides/module-api.md
> +Assim como o [Opções de linha de comando](https://docs.cypress.io/guides/guides/command-line), você pode passar opções
```suggestion
Assim como as [opções de linha de comando](https://docs.cypress.io/guides/guides/command-line), você pode passar opções 
```

2021-09-06 13:30 UTC, wlsf82 commented on pages/guides/module-api.md
> +|   global    |     boolean      | Executar em modo global mode                                                                                         |
```suggestion
|   global    |     boolean      | Executar em modo global                                                                                         |
```

2021-09-06 13:30 UTC, wlsf82 commented on pages/guides/module-api.md
> +| testingType |      string      | Especifique o tipo de testes a serem executados ou e2e ou componente. Padrões para e2e                              |
```suggestion
| testingType |      string      | Especifique os tipos de testes a serem executados ou e2e ou componente. Padrões para e2e                              |
```

2021-09-06 13:31 UTC, wlsf82 commented on pages/guides/module-api.md
> +argumentos de linha de comando fornecidos pelo usuário usando a mesma lógica que o cypress run usa.
Para não ficar usando... usa, recomendo:

```suggestion
argumentos de linha de comando fornecidos pelo usuário usando a mesma lógica que o cypress run utiliza.
```

2021-09-06 13:32 UTC, wlsf82 commented on pages/guides/module-api.md
> +[repita os testes para encontrar testes instáveis](https://github.com/bahmutov/cypress-repeat) e para
```suggestion
[repetir os testes para encontrar testes instáveis](https://github.com/bahmutov/cypress-repeat) e para 
```

2021-09-06 13:34 UTC, wlsf82 requested changes
@Wil-g2, obrigado pela contribuição!

Deixei alguns ajustes antes de seguirmos adiante com o merge.

@pedrohyvo, vou deixar a revisão final contigo. 😉

2021-09-19 12:54 UTC, wlsf82 commented
@pedrohyvo, pode fazer a revisão final?

2021-09-21 20:15 UTC, pedrohyvo requested changes
@Wil-g2 parabéns pela contribuição mano, apenas um ajuste simples e a sua tradução está pronta para o merge! 🚀 🔥

2021-09-21 20:15 UTC, pedrohyvo commented on pages/guides/module-api.md
> +Executa testes do Cypress via Node.js e resolve com todos os resultados de teste. Veja a receita do [Cypress Módulo API](https://github.com/cypress-io/cypress-example-recipes#fundamentals).
Adicionar bloco [TODO] acima do texto onde contem links de páginas que ainda não foram traduzidas.

2021-09-21 20:15 UTC, pedrohyvo commented on pages/guides/module-api.md
> +Assim como as [opções de linha de comando](https://docs.cypress.io/guides/guides/command-line) para o cypress run,
Adicionar TODO

2021-09-21 20:15 UTC, pedrohyvo commented on pages/guides/module-api.md
> +Assim como as [opções de linha de comando](https://docs.cypress.io/guides/guides/command-line), você pode passar opções
Adicionar linha TODO

2021-09-27 02:29 UTC, Wil-g2 commented on pages/guides/module-api.md
> +Executa testes do Cypress via Node.js e resolve com todos os resultados de teste. Veja a receita do [Cypress Módulo API](https://github.com/cypress-io/cypress-example-recipes#fundamentals).
Adicionei para os links que você comentou na PR, ou precida ser nos demais links também essa parte fiquei com dúvida?

2021-09-27 14:35 UTC, pedrohyvo commented on pages/guides/module-api.md
> +Executa testes do Cypress via Node.js e resolve com todos os resultados de teste. Veja a receita do [Cypress Módulo API](https://github.com/cypress-io/cypress-example-recipes#fundamentals).
@Wil-g2 todos os blocos de texto que possuem links que não foram traduzidos ainda devem ter essa linha TODO acima, somente aqueles links que estão fora do escopo da tradução que não precisamos nos preocupar, tá bem?

2021-09-28 18:58 UTC, pedrohyvo commented
@all-contributors please add @Wil-g2 for code

2021-09-28 19:05 UTC, pedrohyvo approved these changes

2021-09-28 19:05 UTC, merged

2021-09-28 19:06 UTC, pedrohyvo commented
@Wil-g2 parabéns pela contribuição, fique à vontade para pegar qualquer outra página da documentação 🚀