The test runner core concepts
pedrohyvo/cypress-docs-pt-br pull request #85
Opened 2021-11-08 15:36 UTC by Lubambo

A página original contém ícones dentro do texto com tags <svg>. Como o github permite inserir svg através da tag <img>, foi necessário baixar estes arquivos e adicioná-los no projeto (dentro da pasta icons) para fazer a referência no atributo src da tag <img>.

Para não deixar o texto desalinhado, tive de ferir a MD013 por causa das tags <img> na seção Finding Selectors (Encontrando Seletores).

2021-11-09 14:10 UTC, pedrohyvo requested changes
@Lubambo parabéns pela contribuição! Deixei alguns comentários e gostaria que você adicionasse a página ao README também. Outra coisa, você não acha que consegue resolver a issue do lint, não?

2021-11-09 14:10 UTC, pedrohyvo commented on pages/core-concepts/the-test-runner.md
> +### Pairando sobre os Comandos
Pairando ficou estranho não?

2021-11-09 14:10 UTC, pedrohyvo commented on pages/core-concepts/the-test-runner.md
> +Cada comando e asserção, quando pairado sobre, restaura a Aplicação em Teste (lado direito do Executor de Testes) para o
pairado também ficou estranho

2021-11-09 14:10 UTC, pedrohyvo commented on pages/core-concepts/the-test-runner.md
> +> um consumo extremamente alto de memória no seu navegador, você pode diminiuir o `numTestsKeptInMemory` na sua [configuração](../references/configuration.md#Global)
Corrigir a palavra diminuir

2021-11-09 14:10 UTC, pedrohyvo commented on pages/core-concepts/the-test-runner.md
> +[abridor de arquivo preferido](../tooling/ide-integration.md#Preferência-do-Abridor-Arquivo) e destaca a linha e coluna
visualizar de arquivo, seria mais interessante, o que acha?

2021-11-09 14:10 UTC, pedrohyvo commented on pages/core-concepts/the-test-runner.md
> +seu [abridor de arquivo preferido](../tooling/ide-integration.md#Preferência-do-Abridor-Arquivo);
mesma coisa aqui também

2021-11-09 14:10 UTC, pedrohyvo commented on pages/core-concepts/the-test-runner.md
> +
Adicionar o voltar para o topo

2021-11-09 14:11 UTC, pedrohyvo commented on icons/copy.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="copy" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="svg-inline--fa fa-copy fa-w-14" style="color: i
Dá uma olhada nisso aqui - https://stackoverflow.com/questions/31469134/how-to-display-multiple-lines-of-text-in-svg

2021-11-10 01:27 UTC, Lubambo commented on pages/core-concepts/the-test-runner.md
> +Clicar neste link abrirá o seu [abridor de arquivo preferido](../tooling/ide-integration.md#Preferência-do-Abridor-Arquivo).
Realmente, muito melhor!

2021-11-10 01:34 UTC, Lubambo commented
Correções feitas. =]

Consegui resolver a issue do lint: fiz os ajustes das dimensões no próprio arquivo `.svg`, fixando em 15px de largura, dessa forma não preciso utilizar a tag `<img>`, economizando caracteres.

Fecho esse pull request e envio outro com os ajustes?

2021-11-10 14:08 UTC, pedrohyvo commented
@Lubambo ainda está apresentando um erro no lint, você pode manter esse mesmo PR também, tá?

2021-11-11 14:29 UTC, closed without merging